### PR TITLE
Dockerize app

### PR DESCRIPTION
**Pull request by uLan08**
Fixes issue #25

Changes: Added `.dockerignore` and `Dockerfile` and update README for instructions on using Docker. Used alpine as base image to produce a smaller size image.

### CODE REVIEW

**Comment by wildan3105** [comment]
Hi, could you show me the screenshot that app works? Maybe from your terminal showing the app run within Docker :ok_hand:

**Comment by uLan08** [comment]
working-docker
working-docker2
Here ya go

**Comment by wildan3105** [comment]
Okay then I assume that worked well within Docker :ok_hand:

**Comment by uLan08** [comment]
Thanks! :whale:

**Pull request merged**
