### PR TITLE
Modularized the UI

### PR DESCRIPTION
**Pull request by IOAyman**
Separated the UI into different partials.

Handling 404 requests

### CODE REVIEW

**Comment by IOAyman** [comment]
Oh, this happens to resolve #34!  (Didn't notice the issue before :D)

**Comment by wildan3105** [comment]
Could you share the 404 page here please @IOAyman ?

**Comment by IOAyman** [comment]
@wildan3105, What do you mean?  
There's a very basic one [in this PR](https://github.com/wildan3105/github-langs/pull/35/files#diff-f0dfebf06e7895b8dc771f23f4f7a6ab). And I just opened #36, if somebody would make it prettier.

**Comment by wildan3105** [comment]
Hi @IOAyman, thank you very much for your PRs and issue! But I'd like to give a chance to other contributor to fix #24 first before merge this PR :) Is that okay with you?

**Comment by IOAyman** [comment]
@wildan3105, Oh sure :)

**Comment by wildan3105** [comment]
Hi @IOAyman, please resolve this conflicts since the previouse PR made a change #37 

Sorry for the inconvenient :disappointed:

**Comment by IOAyman** [comment]
@wildan3105, Ok, I'll rebase.

**Comment by wildan3105** [comment]
Thanks again @IOAyman ! Maybe you'd like to be an active contributors for this project :wink:

**Pull request merged**
