### PR TITLE
Limit number of languages to 20

### PR DESCRIPTION
**Pull request by juancuiule**
Fixes issue #33 

Changes: limited the number of languages in the chart to 20

Screenshots for the change:
screenshot from 2017-10-11 19 35 41

### CODE REVIEW

**Comment by wildan3105** [comment]
Thanks for such a quick PR! Did you test it for the user that has repo < 20? And I think we should add label below the chart like : `we only show top 20 language` (label only shown when user has repo > 20).

And based on #33, sum up to `others` would be good, placing that value at right hand of the chart, again, only if user has repo > 20. Will wait for your change! :+1:

**Comment by juancuiule** [comment]
@wildan3105 I tested it and everything works ok with users with less than 20 languages... I can add that label and try to implement the "others" bar. Should be making some commits in a few hours.

**Comment by wildan3105** [comment]
Hi @juancuiule could you show the screenshot of the results?

**Comment by juancuiule** [comment]
Here is the latest screenshot with the change:
screenshot from 2017-10-12 06 19 37

**Comment by wildan3105** [comment]
Thank you so much @juancuiule ! Maybe you'd like to be an active contributors for this project :wink:

**Comment by wildan3105** [comment]
#40 @juancuiule I made an issue about the bug after applying this PR

**Pull request merged**
