### PR TITLE
beautified search bar, footer & added emojis

### PR DESCRIPTION
**Pull request by PREMPRAKASHSINGH**
Fixes issue #1 

Changes: beautified search bar & footer and added emojis based on no of repos

Screenshots for the change:
image

### CODE REVIEW

**Comment by wildan3105** [comment]
Hi please refer the latest `lib/controller.js` and `views/layouts/main.handlebars`  since it has gone viral and many PRs are merged :smile: Please resolve this conflicts on your local machine :+1: 

Keep up the good work @PREMPRAKASHSINGH

**Comment by PREMPRAKASHSINGH** [comment]
Hey @wildan3105 , Why it is failing? I resolved the conflicts. Conflicts was because whoever added those charts code, he added it in the head section instead of at the end of body. This is what i think i good practice to first load the page then perform js operations

**Comment by wildan3105** [comment]
Hi @PREMPRAKASHSINGH, thank you for your resolve :) I really sorry for this, could you move those chart code at the end of the body so your PR will pass the test? thank you very much

**Comment by juancuiule** [comment]
Hey @PREMPRAKASHSINGH, I added that code in the head, it doesn't have to wait for any html element to be rendered, that's why I placed it there...

**Comment by wildan3105** [comment]
@juancuiule Could we place those code in `js` file and include that in `script` tag? I don't have much experiences about the chart. Will wait for you all feedback @juancuiule and @PREMPRAKASHSINGH :)

**Comment by PREMPRAKASHSINGH** [comment]
It shows no conflicts but the travis-ci test is failing why?

**Comment by wildan3105** [comment]
@PREMPRAKASHSINGH You need to run `npm run test` to follow eslint style and pass the test

**Comment by juancuiule** [comment]
yeah of course, it was my bad doing everything there, we could also create a css file for the styles that are there. Do yo want me to do that? @wildan3105, what do you think @PREMPRAKASHSINGH ?

**Comment by PREMPRAKASHSINGH** [comment]
okay doing it right now.

**Comment by wildan3105** [comment]
@juancuiule Please make an issue about this `style` problem. I will add `hacktoberfest` label if you want. Just to make the discussion clean and focused.

Thanks for the enthusiasm guys! @PREMPRAKASHSINGH @juancuiule

**Comment by PREMPRAKASHSINGH** [comment]
sure @juancuiule  go ahead, that would be cleaner approach. i am doing npm run test right now :)

**Comment by juancuiule** [comment]
So just to be sure, @PREMPRAKASHSINGH will you create the js file with the chart code in order to fix this conflict?

**Comment by PREMPRAKASHSINGH** [comment]
right now there are no conflict. My PR is just failing travis-ci test so that's i am doing npm test.

**Comment by PREMPRAKASHSINGH** [comment]
Cool @wildan3105 now the checks are passing and you can merge my PR

**Comment by wildan3105** [comment]
Hi @PREMPRAKASHSINGH, sorry, turns out it had conflict with previous PR #8, could you run `npm run test` again please? So sorry

**Comment by PREMPRAKASHSINGH** [comment]
Yes doing it.

**Comment by PREMPRAKASHSINGH** [comment]
@wildan3105 see now

**Comment by wildan3105** [comment]
Thanks! @PREMPRAKASHSINGH, really good work :handshake:

**Comment by PREMPRAKASHSINGH** [comment]
Welcome @wildan3105 
Happy Hacktoberfest!

**Pull request merged**
