### PR TITLE
Added Loading Animation During API-Fetch

### PR DESCRIPTION
**Pull request by azharakbar**
Signed-off-by: Mohammed Azhar <azharakbar@gmail.com>

Fixes issue #15 

Changes: Displays A spinning loader till the API call returns with a response to the client browser.

### CODE REVIEW

**Comment by azharakbar** [comment]
@wildan3105 Hi, I have opened the new PR .. :)

**Comment by wildan3105** [comment]
Hi, finally thanks for the PR! But I see two things here, after applying your code to my local machine : 

space
space2

- [ ]  Could you remove the space between `search bar` and `result` ?
- [ ]  Could you add space between `search` bar and `loading animation` when fetching data ?

**Comment by azharakbar** [comment]
@wildan3105 Sure .. will work on it nw .. :)

**Comment by azharakbar** [comment]
@wildan3105 I have done it .. :) .. Pls check the PR .. :)

**Comment by wildan3105** [comment]
Could you show me the screenshot of the page when we get the result of user's repo? @azharakbar

**Comment by azharakbar** [comment]
@wildan3105 Sure ... :) I have corrected it ... will raise the PR now .. :)

**Comment by azharakbar** [comment]
@wildan3105 I have cleared it ... and raised the PR .. :)

**Comment by azharakbar** [comment]
@wildan3105 Thank You ...

**Comment by azharakbar** [comment]
@wildan3105 I am not getting the loading effect in the website ... Why is it so ??

**Comment by wildan3105** [comment]
Cool! Thanks for the effort :+1: Really appreciate your changes :100:

**Comment by wildan3105** [comment]
Calm down, still building :smile:

**Comment by azharakbar** [comment]
@wildan3105 Hehe ... thanks man .. it was good contributing for this project ... now shall we convert this into a **Single Page Application** ??

**Comment by wildan3105** [comment]
@azharakbar thanks for the enthusiasm, but right now my focus is [this](https://github.com/wildan3105/github-langs/issues/22). So unless that is resolved, maybe I'll add your suggestion as a todo-list after that issue :)

**Comment by azharakbar** [comment]
@wildan3105 Ok ... :)

**Pull request merged**
