### PR TITLE
fixed lang-stat not showing

### PR DESCRIPTION
**Pull request by abhagsain**
Fixes issue #101

Changes: in ```chart.js``` legend display was being shown conditionally causing to toggle the lang-stat label

Here's the working screencast:
githulang

### CODE REVIEW

**Comment by wildan3105** [comment]
Hi @abhagsain , turns out, when bar is colorful (non-white), the color that appeared next to "Language stats" is the highest-language repo (in your example is yellow). For this reason, can we just get ride the bar next to "Language stats" word wheter it's colorful/white graph?

**Comment by abhagsain** [comment]
Hi There! Did you ask me to remove the coloured bar right?
Here's the screencast

githublang-2

**Comment by wildan3105** [comment]
Nice! Good job @abhagsain :+1:

**Comment by wildan3105** [comment]
Anw, don't forget to star this repo! @abhagsain :wink:

**Pull request merged**
