### PR TITLE
Add SASS support and restructure style files for SASS

### PR DESCRIPTION
**Pull request by Klubiniecki**
Fixes issue #73 - first refactor to prepare for further work

Changes:
- adds SASS to the project
- adds gulpfile.js to support SASS
- restructures style files to work with SASS

Screenshots for the change:
No visual or functional changes to the project

### CODE REVIEW

**Comment by wildan3105** [comment]
Thanks for the PR! @Klubiniecki I'll review it first

**Comment by wildan3105** [comment]
Could you pass the codacy style?

**Comment by wildan3105** [comment]
Hi @Klubiniecki, could we `ignore` the `cache` directory?

**Comment by Klubiniecki** [comment]
@wildan3105 , sounds good but I don't know how to to it :)

**Comment by wildan3105** [comment]
Turns out your change made some error, will check it first

**Comment by Klubiniecki** [comment]
Oh oh. It worked locally without any issues, maybe it's some Heroku settings? Let me know what you'll find.

**Comment by wildan3105** [comment]
Okay, I resolved it and ignore the `.sass-cache` dir, thanks @Klubiniecki

**Comment by Klubiniecki** [comment]
Sweet, good job! I'll upload first dark theme design screenshots in the evening, so we can discuss :)

**Pull request merged**
