### PR TITLE
Add vertical graph that dinamically display programming language based on user's repos using Chart.js

### PR DESCRIPTION
**Pull request by juancuiule**
Fixes issue #2 

Changes: Added Chart.js cdn and 2 functions.
One takes care of parsing the data-languages attribute in the div with id = chart-container to and object
and the other one creates the chart inside a canvas with that information

Screenshots for the change:
Screenshot

### CODE REVIEW

**Comment by juancuiule** [comment]
I think that it's possible to randomize, I was also wondering if we could get the same colors that github uses for each language, do you know if the API can tell us that? if not we can create an dictionary with language:color relation. Waiting for your feedback too

**Comment by wildan3105** [comment]
AFAIK, github used [linguist](https://github.com/github/linguist) to determine the language of the repo. But I don't know if it contains the color. After random googling, I found this repo [github-colors](https://github.com/ozh/github-colors) that display all the color for each language. Even if we want to make it random, I want to make it consistent so user will see one color for each language even though they switch the user they're looking into, any feedback? 

For me, one color is good as far as the font-style and color well read :+1:

**Comment by juancuiule** [comment]
I made a mistake committing another file, will fix it soon

**Comment by wildan3105** [comment]
Hi please resolve the conflicts on your local machine :) @juancuiule

**Comment by wildan3105** [comment]
Another one, could you show me the latest screenshot of the chart you applied ? @juancuiule

**Comment by juancuiule** [comment]
It should be ok to merge now @wildan3105 
it looks like this now:
screenshot

**Comment by wildan3105** [comment]
Nice! That's even better :+1:

**Comment by wildan3105** [comment]
#33 @juancuiule Maybe you want to take a look into that issue :ok_hand:

**Pull request merged**
