### PR TITLE
Update main.handlebars

### PR DESCRIPTION
**Pull request by xepozz**
Fixes issue #11 

Changes: Changing main.handlebars

Screenshots for the change:

### CODE REVIEW

**Comment by wildan3105** [comment]
Hi @xepozz, thank you very much for this PR (also #14). But, since this PR would fix #11 that I gave to @juancuiule, I'll wait his PR to fix that issue first. By doing this I want to make sure that other contributor's code will has impact to this project. Really appreciate :)

**Comment by juancuiule** [comment]
@wildan3105 if this code is ok with you, don't wait for my pr and merge it anyway

**Comment by wildan3105** [comment]
Okay will check it first @xepozz @juancuiule

**Comment by wildan3105** [comment]
Thanks! @xepozz

**Pull request merged**
