### PR TITLE
save chart as an image

### PR DESCRIPTION
**Pull request by juancuiule**
Adds a feature that lets save the chart as an image

Screenshot:
screenshot from 2017-10-13 21-30-34

### CODE REVIEW

**Comment by wildan3105** [comment]
Hi @juancuiule. thanks again for the PR! Could you show me the image saved from that graph? And I think button from #54 PR is more convenient :) Thanks again!

**Comment by wildan3105** [comment]
#60

**Comment by juancuiule** [comment]
Image saved from the graph:
download

**Comment by juancuiule** [comment]
This works with colored graph too
download

**Pull request merged**
