### PR TITLE
toggle button color change fix

### PR DESCRIPTION
**Pull request by roh777**
Fixes issue #64 

Changes: 
* two new css classes for active and inactive stages
* changes in body.handlebars (added button id)
* chart.js toggle function updated.
togglebutton

### CODE REVIEW

**Comment by wildan3105** [comment]
Wow that's fast! @roh777 Thank you but I need to wait until @jakezaleski submit PR and see if I could merge you both solutions :) Thanks :+1:

**Comment by roh777** [comment]
Alright, Thanks. Happy to help 👍

**Comment by wildan3105** [comment]
Sorry :( @roh777, I think I just deleted your `style`, could you resolve the conflict because of the previous PR? Thank you very much

**Comment by roh777** [comment]
Okay. So should I make a new PR request with style files only?

**Comment by wildan3105** [comment]
Would be good if you make a PR again as same as this but without a conflict so I could merge it immediately :smile: :+1: @roh777, thanks again!

**Comment by roh777** [comment]
I pulled the recent changes you made in other files(the one's in which you lost style classes), now I have committed again with button styles and updated my master branch(this pull request).

I think you should be able to merge without conflicts. TPing me, if something comes up.

**Pull request merged**
