### PR TITLE
Chart color by language name

### PR DESCRIPTION
**Pull request by iamham**
Chart color (by language) toggle button
- Using https://github.com/doda/github-language-colors/blob/master/colors.json
- Toggle button 
- Black border
- Hide legend when in multiple color mode

Issue: #60 
Screenshot: 
- single color chart
screen shot 2560-10-14 at 19 32 30

- multiple color chart
screen shot 2560-10-14 at 19 32 46

### CODE REVIEW

**Comment by wildan3105** [comment]
Is that the screenshot of the former chart? What about your result? @iamham 
Thanks anyway!

**Comment by iamham** [comment]
My bad just re-upload the screenshot 😁

**Comment by wildan3105** [comment]
Thanks! Could you add a `toggle button` so user could choose wheter that chart will display full-color or just white, and I think the `legend` now is a little bit confusing since it represents the most language used, what do you think about that? @iamham

**Comment by iamham** [comment]
Sure I'll add that, agree legend is a bit confusing but couldn't think of anything better Haha @wildan3105

**Comment by wildan3105** [comment]
Okay thanks :) Will wait for your commit. I would prefer to hide the legend from the `chart` :+1:

**Comment by wildan3105** [comment]
And maybe make the border bar to be `black` :+1:

**Comment by wildan3105** [comment]
Could you share the screenshot again with `toggle button`, please @iamham ?

**Comment by iamham** [comment]
Sure, edited ;D @wildan3105

**Comment by wildan3105** [comment]
Okay, thanks for the work @iamham ! :100:

**Pull request merged**
