### PR TITLE
Updated the footer look and deleted language text.

### PR DESCRIPTION
**Pull request by Ceciceciceci**
Fixes issue #9 

Changes: [Added Div around elements to be hidden and updated CSS for mastfoot]

### CODE REVIEW

**Comment by wildan3105** [comment]
Hi @Ceciceciceci, since previous PR (#10) made the change on `views/layouts/main.handlebars`, please refer to the latest file and resolve the conflicts :)

**Comment by Ceciceciceci** [comment]
Fixed conflict!

**Comment by wildan3105** [comment]
Hi @Ceciceciceci, could you make the position of footer at bottom of the page? Because it looks like this if I apply your change : 

footer

**Comment by wildan3105** [comment]
Sorry to close this PR because it's already solved by [this](https://github.com/wildan3105/github-langs/pull/29)

If you'd like to contribute, please see the issue(s) :)
Happy hacking

**Pull request closed without merging**
