### PR TITLE
Multiple fixes

### LINKED ISSUE #32: Fix CI test
**Current behavior:**
The current CI test script is passing **at all times**, even if it should not.

**Expected behavior:**
The CI test should fail if there are code style violations.

The [current][0] test command is trying to auto-fix any errors. So it will *not* report anything in most cases.
```bash
eslint --fix lib/*.js index.js
```

[0]: https://github.com/wildan3105/github-langs/blob/e17dfde158098716a4413860a0dcf186c0d0c8a8/.travis.yml

### PR DESCRIPTION
**Pull request by IOAyman**
Changelog:

- [x] Fix code style issues caused in earlier commits
- [x] Move `eslint` dependency to `dev-dependencies`, because that's what it is.
- [x] Docker: Upgraded node to the latest 8.6 and switched to `npm start` as entry command.  
It's a more convenient/consistent way to launch the app. If the command changes, you'd only change it in one place (in `package.json`)
- [x] Changed the `npm start` script to use `nodemon` instead of standard `node`.  
This is helpful in a development process; it reloads the changes to the source code files as soon as they are saved.  
- [x] Resolve #32

### CODE REVIEW

**Comment by IOAyman** [comment]
I'll rebase on master ASAP.  Glad to see how active this repo is 😉

**Comment by IOAyman** [comment]
@wildan3105, rebased!

**Comment by wildan3105** [comment]
Okay will review it first :) @IOAyman

**Comment by wildan3105** [comment]
Thanks again for the minor updates! @IOAyman, Btw, should we just ignore the `package-lock.json`? I don't see any functionality on that

**Comment by wildan3105** [comment]
Hi @IOAyman, turned out it error again in heroku, look at this :+1: 

heroku

**Comment by wildan3105** [comment]
Hi, the app on heroku started to crush again, here is the screenshot : 

heroku

Any idea on that?

**Comment by IOAyman** [comment]
How are you setting the env variables in Heroku?

**Comment by wildan3105** [comment]
Sorry, turns out I had to add `env` vars manually from the heroku-cli. Solved.

**Pull request merged**
