### PR TITLE
Display more than 100 repos

### PR DESCRIPTION
**Pull request by Leocardoso94**
Fixes issue #3 

Changes: recursive call to github api

Screenshots for the change:
image

### CODE REVIEW

**Comment by wildan3105** [comment]
Hi @Leocardoso94, do you tried several times? Sometimes I still got 100 repos for user more than 100 repos.

**Comment by Leocardoso94** [comment]
Hi @wildan3105, I fix this. Can you check?

**Comment by wildan3105** [comment]
Hi @Leocardoso94, I have looked that. But sadly, for user with repos > 200, the pattern still the same. Only displayed 200 repos. Image below : 



Any idea on that?

**Comment by Leocardoso94** [comment]
image

@wildan3105 ,  sorry i fix that too

**Comment by wildan3105** [comment]
Thanks! I tested with user that has 100+, 200+, and 300+, all worked! Maybe in the frontend I need to add `100++` tag and also display the actual repos the user has. Thank you, well done :+1:

**Comment by Leocardoso94** [comment]
I really liked the project, if you need any more help, you can tell me.

**Comment by wildan3105** [comment]
Sure @Leocardoso94, Many issue(s) will be coming up! Get ready :100:

**Comment by wildan3105** [comment]
#2 If you want to take a look

**Comment by Leocardoso94** [comment]
Ok. I'll see this

**Pull request merged**
