### PR TITLE
Enable monitoring in production environment only

### PR DESCRIPTION
**Pull request by IOAyman**
***Changelog:***

- [x] Enable monitoring in production environment only 
- [x] Added .env.sample 

- - -
/cc @wildan3105, Please do not forget to set the `NODE_ENV=production` environment variable in Heroku before deploying this 😉

### CODE REVIEW

**Comment by wildan3105** [comment]
Ah you always got the detail! Thanks :+1: @IOAyman

**Comment by wildan3105** [comment]
Is that okay to not **require** `dotenv` package when we call `process.env`? Just to make sure your change works

**Comment by IOAyman** [comment]
@wildan3105, You're welcome 😄 

Long answer short; yes, you don't have to require `dotenv` each time you use `process.env`.

***What is `process.env`?***
As you should know, NodeJS programs run as a single process, it does not -by default- take advantage of multiple cores in the machine.  
Whenever a NodeJS program is run, it creates a global variable called `process` which holds a ton of information about the process and the environment it's running on, one of which is the `process.env` variable; This one holds the environment variables in the system.  

***Is that okay to not require `dotenv` package when we call `process.env`?***
`dotenv`, when called, just reads some extra variables -that might not be set in the system- from a file (typically named `.env`, but could be anything else), parses those them and assigns them to `process.env`.  
So, there are two possibilities to answer your question:
1. If you are loading some static data in the env variables, for instance an auth token, then you don't need to call `dotenv` each time, just load it once at start-up and those variables will be available for the all modules, since the same `process` is available to all of them.
2. However, if you are expecting the env vars to change at runtime, then you should call `dotenv` to load any changes there might have been.

**Comment by wildan3105** [comment]
Great! thank you for the explanation @IOAyman :+1:

**Comment by IOAyman** [comment]
😄 😉

**Comment by IOAyman** [comment]
@wildan3105, didn't see your edited message. Sorry.

You mean the code from this PR is throwing that error?

**Comment by wildan3105** [comment]
Yes that's right @IOAyman, but I confused because your PR is passed the CI test :confused:

**Comment by IOAyman** [comment]
Please make sure you have your env vars well setup then!  Either via `.env` or otherwise.

**Comment by wildan3105** [comment]
Yes I did that but still got error message..

**Comment by wildan3105** [comment]
Or it only applied on certain Nodejs version? What version do you use? @IOAyman

**Comment by IOAyman** [comment]
I'm running 8.6.0. But it's not a NodeJS thing.  
You must be missing something. Have you properly cloned that branch? Is your git env clean?


I have just cloned the same branch on a clean server and ran the docker image, works just fine.

**Comment by wildan3105** [comment]
Okay I'll double check it again :ok_hand:

**Comment by IOAyman** [comment]
Just make sure you don't have modified files when testing this.  
Here's a quick script to test on a detached branch
```bash
git remote add ioayman https://github.com/IOAyman/github-langs.git
git fetch ioayman
git checkout -f ioayman/patches
cat > .env << EOF
CLIENT_ID=xxx
CLIENT_SECRET=xxx
#NODE_ENV=production
#OPBEAT_APP_ID=
#OPBEAT_ORGANIZATION_ID=
#OPBEAT_SECRET_TOKEN=
EOF
npm start
```

- - -
PS: I don't receive notifications when you edit your messages

**Comment by wildan3105** [comment]
Okay I'll check it. Thanks! @IOAyman

**Comment by wildan3105** [comment]
This PR is no longer relevant.

**Pull request closed without merging**
