### PR TITLE
Make animated toggle color button

### PR DESCRIPTION
**Pull request by ibokg**
Fixes issue #125 

Changes: Make animated toggle color button.

Screenshots for the change:
New Project
New Project (1)

### CODE REVIEW

**Comment by wildan3105** [comment]
Hi @ibokg, thanks for the PR. Could you provide video showing that animated toggle color button?

**Comment by ibokg** [comment]
@wildan3105 https://gofile.io/?c=79V4P7

**Comment by wildan3105** [comment]
Thanks @ibokg, but could you make the position of toggle button equal (height) to the download button? Because I saw in the video that the toggle button's position is higher than download button.

**Comment by wildan3105** [comment]
Hi @ibokg, turns out the simpler solution is provided by @fuzztone313 in #126 and it did solve the problem. So I'm sorry to decline your PR, but you always can contribute to open an issue / make another PR to enhance this project though. Thank you :pray:

**Pull request closed without merging**
