### PR TITLE
#16 added icon if the user is an organization

### PR DESCRIPTION
**Pull request by ChrisMcNulty91**
Fixes issue #16 

Changes: Added a blue check icon if the user type is organization

language-checker

### CODE REVIEW

**Comment by wildan3105** [comment]
Hi @ChrisMcNulty91 would you like to decrease the size of badge and make the position like this : 

badge copy

**Comment by ChrisMcNulty91** [comment]
@wildan3105 Sure I can look at doing that

**Comment by ChrisMcNulty91** [comment]
@wildan3105 This any better?
language-checker

**Comment by wildan3105** [comment]
That's awesome! Will review first since many PRs queued and waiting for the merge. But good job @ChrisMcNulty91 ! :+1:

**Comment by wildan3105** [comment]
Hi @ChrisMcNulty91, since the `lib/controller.js` and `views/layouts/main.handlebars` changed recently because previouse PR ( #21 ), could you resolve this conflicts first? Thank you very much :)

**Comment by ChrisMcNulty91** [comment]
@wildan3105 I'll get to it as soon as I'm back at a computer

**Comment by wildan3105** [comment]
Hi @ChrisMcNulty91, are you still working on this? Let me know if you need anything :) Thanks!

**Comment by ChrisMcNulty91** [comment]
@wildan3105 Haven't had a lot of spare time to resolve the conflict. I hope to get it done today

**Comment by ChrisMcNulty91** [comment]
@wildan3105 I pulled the latest code and I am getting this error when searching for a user 

`SyntaxError: Unexpected token u in JSON at position 0
    at Object.parse (native)
    at Request.request.get [as _callback] (C:\GIT_Projects\hacktober\github-langs\lib\controller.js:89:27)
    at self.callback (C:\GIT_Projects\hacktober\github-langs\node_modules\request\request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (C:\GIT_Projects\hacktober\github-langs\node_modules\request\request.js:878:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)`

**Comment by wildan3105** [comment]
I think the cause is the `proxy` so the `request` package won't get data from API. Do you use proxy on your networks? @ChrisMcNulty91

**Comment by ChrisMcNulty91** [comment]
@wildan3105 I see the setting for the proxy. I'll add it in now and see if it works

**Comment by wildan3105** [comment]
Thanks for the PR! @ChrisMcNulty91 But I think I should change some style since I got result like this : 

badge

**Pull request merged**
