### PR TITLE
Code Clean up and small tweaks

### PR DESCRIPTION
**Pull request by udithishara**
Fix Scrollbars coming up on mobile view
Small CSS tweaks
Add "Save graph as image" from TODO list

Changes: Mentioned Above

Screenshots for the change:

image

@wildan3105 Please review when you have a chance

### CODE REVIEW

**Comment by wildan3105** [comment]
Hi @udithishara, thanks for the PR! Could you also show me the image saved from that graph? Sorry for the late reply

**Comment by udithishara** [comment]
Hey @wildan3105 no problem

It's pretty much the same image if you open the canvas image in a new tab, and it has a transparent background

Saved .png image : ( and you cant see the font colors cause git background and char colors are white 😩 )

image

**Comment by wildan3105** [comment]
Sorry @udithishara, apparently I have to open an issue about toggle click first (TODO list #7 in `README.md`) 
But it's a great addition though! :+1:

**Comment by udithishara** [comment]
@wildan3105 yeah sure, let me know if i need to do any modifications

**Comment by wildan3105** [comment]
Okay :+1: @udithishara

**Comment by wildan3105** [comment]
Hi @udithishara I think you could work on #68 if you'd like :)

**Pull request closed without merging**
